#!/usr/bin/env zsh
# Prepares server for use

if ! command -v zsh &> /dev/null
then
    echo "ZSH could not be found, please install."
    exit
fi

if [ "$(basename $SHELL)" != "zsh" ]; then
    echo "ZSH needs to be the default shell, please run:"
    echo "chsh -s $(which zsh)"
    echo "Then log out and in."
    exit
fi

if [ -z $ZSH_VERSION ]; then
    echo "This script needs to be run from zsh."
    exit
fi

# Ensure important directories exist
if [ ! -d $HOME/.local/ ]; then; mkdir $HOME/.local; fi
if [ ! -d $HOME/.local/bin ]; then; mkdir $HOME/.local/bin; fi
if [ ! -d $HOME/.R/ ]; then; mkdir $HOME/.R; fi
if [ ! -d $HOME/.R/packages ]; then; mkdir $HOME/.R/packages; fi

# Make sure antibody is in PATH if available
if [ ! -d ${ZDOTDIR:-~}/.antidote ]
then
    echo "Antidote could not be found, do you want me to install it? (Y/N)"
    echo "Installing will run: git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-~}/.antidote"

    read -k 1 REPLY; echo ''
    if [[ $REPLY =~ ^[Yy]$ ]]; then
	git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-~}/.antidote
    fi
    echo "Please rerun the installer."
    exit
fi

echo "Create symlinks in home folder (Y/N)"
read -k 1 REPLY; echo ''
if [[ $REPLY =~ ^[Yy]$ ]]; then

    if [[ -z "$SERVERCONFIG" ]]; then
        echo "Location of server-config folder (added to .zshenv):"
        confloc="$(pwd)"
        vared confloc
        echo "#Automatically generated by server-config/setup.sh\nexport SERVERCONFIG=\"$confloc\"\n" > $HOME/.zshenv
    fi

    source ~/.zshenv
    if [ ! -f $SERVERCONFIG/exports.local ]; then; touch $SERVERCONFIG/exports.local; fi

    echo "All files that would have been overwritten will be backed up to ~/dotfiles_backup/"
    for src in $(find -H `pwd -P` -maxdepth 1 -name '.*' -not -name '.gitignore' -not -name '.DS_Store' -not -name '.editorconfig' -not -path '*.git'); do
        dst="$HOME/$(basename "$src")"

        # If file exists move it to backup
        if [[ -f "$dst" || -d "$dst" || -L "$dst" ]]; then
            if [ ! -d ~/dotfiles_backup/ ]; then; mkdir ~/dotfiles_backup; fi
            mv "$dst" ~/dotfiles_backup
        fi

        # Create symbolic link
        echo "Linking $src to $dst"
        ln -s "$src" "$dst"
    done
    unset src dst
fi

echo ""
echo "Link executables to ~/.local/bin (Y/N)"
read -k 1 REPLY; echo ''
if [[ $REPLY =~ ^[Yy]$ ]]; then
    ln -s $SERVERCONFIG/tmux_startup $HOME/.local/bin/tmux_startup
fi
